from . import product_template
from . import cannafr_news_ept
from . import product_label
from . import product_label_line
from . import cannafr_events_ept
from . import res_users
from . import cannafr_team
from . import cannafr_department
from . import cn_partnership
from . import mass_mailing
from . import ir_qweb
